export const CHAT_CONNECT_SUCCESS = 'CHAT_CONNECT_SUCCESS';
export const CHAT_CONNECT_FAIL = 'CHAT_CONNECT_FAIL';
export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
export const CHAT_SEND_MESSAGE_FAIL = 'CHAT_SEND_MESSAGE_FAIL';
export const CHAT_DISCONNECTED = 'CHAT_DISCONNECTED';
