export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';


export const ALL_ORDER_LIST_REQUEST = 'ALL_ORDER_LIST_REQUEST';
export const ALL_ORDER_LIST_SUCCESS = 'ALL_ORDER_LIST_SUCCESS';
export const ALL_ORDER_LIST_FAIL = 'ALL_ORDER_LIST_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';

// export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

export const SHIPMENT_SAVE_REQUEST = 'SHIPMENT_SAVE_REQUEST';
export const SHIPMENT_SAVE_SUCCESS = 'SHIPMENT_SAVE_SUCCESS';
export const SHIPMENT_SAVE_FAIL = 'SHIPMENT_SAVE_FAIL';

export const USER_SHIPMENT_LIST_REQUEST = 'USER_SHIPMENT_LIST_REQUEST';
export const USER_SHIPMENT_LIST_SUCCESS = 'USER_SHIPMENT_LIST_SUCCESS';
export const USER_SHIPMENT_LIST_FAIL = 'USER_SHIPMENT_LIST_FAIL';

export const ALL_USERS_SHIPMENT_LIST_REQUEST = 'ALL_USERS_SHIPMENT_LIST_REQUEST';
export const ALL_USERS_SHIPMENT_LIST_SUCCESS = 'ALL_USERS_SHIPMENT_LIST_SUCCESS';
export const ALL_USERS_SHIPMENT_LIST_FAIL = 'ALL_USERS_SHIPMENT_LIST_FAIL';

export const ORDER_ITEMS_LIST_REQUEST = 'ORDER_ITEMS_LIST_REQUEST';
export const ORDER_ITEMS_LIST_SUCCESS = 'ORDER_ITEMS_LIST_SUCCESS';
export const ORDER_ITEMS_LIST_FAIL = 'ORDER_ITEMS_LIST_FAIL';

export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL';

export const REVIEW_EDIT_REQUEST = 'REVIEW_EDIT_REQUEST';
export const REVIEW_EDIT_SUCCESS = 'REVIEW_EDIT_SUCCESS';
export const REVIEW_EDIT_FAIL = 'REVIEW_EDIT_FAIL';

export const CONFIRM_DELIVERY_REQUEST = 'CONFIRM_DELIVERY_REQUEST';
export const CONFIRM_DELIVERY_SUCCESS = 'CONFIRM_DELIVERY_SUCCESS';
export const CONFIRM_DELIVERY_FAIL = 'CONFIRM_DELIVERY_FAIL';

export const ORDER_CONFIRM_DELIVERY_REQUEST = 'ORDER_CONFIRM_DELIVERY_REQUEST';
export const ORDER_CONFIRM_DELIVERY_SUCCESS = 'ORDER_CONFIRM_DELIVERY_SUCCESS';
export const ORDER_CONFIRM_DELIVERY_FAIL = 'ORDER_CONFIRM_DELIVERY_FAIL';

export const SHIPPING_ADDRESS_REQUEST = 'SHIPPING_ADDRESS_REQUEST';
export const SHIPPING_ADDRESS_SUCCESS = 'SHIPPING_ADDRESS_SUCCESS';
export const SHIPPING_ADDRESS_FAIL = 'SHIPPING_ADDRESS_FAIL';

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';

export const ORDER_ADD_REVIEW_REQUEST = 'ORDER_ADD_REVIEW_REQUEST';
export const ORDER_ADD_REVIEW_SUCCESS = 'ORDER_ADD_REVIEW_SUCCESS';
export const ORDER_ADD_REVIEW_FAIL = 'ORDER_ADD_REVIEW_FAIL';

export const ORDER_EDIT_REVIEW_REQUEST = 'ORDER_EDIT_REVIEW_REQUEST';
export const ORDER_EDIT_REVIEW_SUCCESS = 'ORDER_EDIT_REVIEW_SUCCESS';
export const ORDER_EDIT_REVIEW_FAIL = 'ORDER_EDIT_REVIEW_FAIL';
