export const PAYMENT_CREATE_REQUEST = 'PAYMENT_CREATE_REQUEST';
export const PAYMENT_CREATE_SUCCESS = 'PAYMENT_CREATE_SUCCESS';
export const PAYMENT_CREATE_FAIL = 'PAYMENT_CREATE_FAIL';

export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL';

export const ADMIN_PAYMENT_LIST_REQUEST = 'ADMIN_PAYMENT_LIST_REQUEST';
export const ADMIN_PAYMENT_LIST_SUCCESS = 'ADMIN_PAYMENT_LIST_SUCCESS';
export const ADMIN_PAYMENT_LIST_FAIL = 'ADMIN_PAYMENT_LIST_FAIL';

export const LIST_ALL_PAYMENTS_REQUEST = 'LIST_ALL_PAYMENTS_REQUEST';
export const LIST_ALL_PAYMENTS_SUCCESS = 'LIST_ALL_PAYMENTS_SUCCESS';
export const LIST_ALL_PAYMENTS_FAIL = 'LIST_ALL_PAYMENTS_FAIL';
