export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST= 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS ='PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const TRACK_PRODUCT_SAVE_REQUEST= 'TRACK_PRODUCT_SAVE_REQUEST'
export const TRACK_PRODUCT_SAVE_SUCCESS ='TRACK_PRODUCT_SAVE_SUCCESS'
export const TRACK_PRODUCT_SAVE_FAIL = 'TRACK_PRODUCT_SAVE_FAIL'

export const SAVE_PRODUCT_REQUEST = 'SAVE_PRODUCT_REQUEST';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAIL = 'SAVE_PRODUCT_FAIL';

export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAIL = 'REMOVE_PRODUCT_FAIL';

export const UPDATE_PRODUCT_SAVE_COUNT = 'UPDATE_PRODUCT_SAVE_COUNT';

export const VIEW_PRODUCT_REQUEST = 'VIEW_PRODUCT_REQUEST';
export const VIEW_PRODUCT_SUCCESS = 'VIEW_PRODUCT_SUCCESS';
export const VIEW_PRODUCT_FAIL = 'VIEW_PRODUCT_FAIL';

export const RECOMMENDED_PRODUCTS_REQUEST = 'RECOMMENDED_PRODUCTS_REQUEST';
export const RECOMMENDED_PRODUCTS_SUCCESS = 'RECOMMENDED_PRODUCTS_SUCCESS';
export const RECOMMENDED_PRODUCTS_FAIL = 'RECOMMENDED_PRODUCTS_FAIL';

export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST';
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAIL = 'PRODUCT_SEARCH_FAIL';

export const USER_FAVORITE_PRODUCTS_REQUEST = 'USER_FAVORITE_PRODUCTS_REQUEST';
export const USER_FAVORITE_PRODUCTS_SUCCESS = 'USER_FAVORITE_PRODUCTS_SUCCESS';
export const USER_FAVORITE_PRODUCTS_FAIL = 'USER_FAVORITE_PRODUCTS_FAIL';

export const USER_VIEWED_PRODUCTS_REQUEST = 'USER_VIEWED_PRODUCTS_REQUEST';
export const USER_VIEWED_PRODUCTS_SUCCESS = 'USER_VIEWED_PRODUCTS_SUCCESS';
export const USER_VIEWED_PRODUCTS_FAIL = 'USER_VIEWED_PRODUCTS_FAIL';
