// export const APPLY_PROMO_SUCCESS = "APPLY_PROMO_SUCCESS";
// export const APPLY_PROMO_ERROR = "APPLY_PROMO_ERROR";
// export const SET_TIMER = "SET_TIMER";

export const REFERRAL_SUCCESS = "REFERRAL_SUCCESS";
export const REFERRAL_ERROR = "REFERRAL_ERROR";

export const GENERATE_REFERRAL_REQUEST = "GENERATE_REFERRAL_REQUEST";
export const GENERATE_REFERRAL_SUCCESS = "GENERATE_REFERRAL_SUCCESS";
export const GENERATE_REFERRAL_ERROR = "GENERATE_REFERRAL_ERROR";

export const GET_USER_REFERRALS_REQUEST = "GET_USER_REFERRALS_REQUEST";
export const GET_USER_REFERRALS_SUCCESS = "GET_USER_REFERRALS_SUCCESS";
export const GET_USER_REFERRALS_ERROR = "GET_USER_REFERRALS_ERROR";

export const GENERATE_REFERRAL_BUTTON_REQUEST =
  "GENERATE_REFERRAL_BUTTON_REQUEST";
export const GENERATE_REFERRAL_BUTTON_SUCCESS =
  "GENERATE_REFERRAL_BUTTON_SUCCESS";
export const GENERATE_REFERRAL_BUTTON_ERROR = "GENERATE_REFERRAL_BUTTON_ERROR";

export const PROMO_CODE_REQUEST = "PROMO_CODE_REQUEST";
export const PROMO_CODE_SUCCESS = "PROMO_CODE_SUCCESS";
export const PROMO_CODE_FAIL = "PROMO_CODE_FAIL";
export const CLEAR_PROMO_CODE = "CLEAR_PROMO_CODE";
export const SET_PROMO_DISCOUNT = "SET_PROMO_DISCOUNT";

export const CREATE_PROMO_REQUEST = "CREATE_PROMO_REQUEST";
export const CREATE_PROMO_SUCCESS = "CREATE_PROMO_SUCCESS";
export const CREATE_PROMO_FAIL = "CREATE_PROMO_FAIL";

export const CLEAR_PROMO_MESSAGE = "CLEAR_PROMO_MESSAGE";

export const PROMO_PRODUCT_REQUEST = 'PROMO_PRODUCT_REQUEST';
export const PROMO_PRODUCT_SUCCESS = 'PROMO_PRODUCT_SUCCESS';
export const PROMO_PRODUCT_FAIL = 'PROMO_PRODUCT_FAIL';

