// supportConstants.js
export const CREATE_TICKET_REQUEST = 'CREATE_TICKET_REQUEST';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL';

export const CREATE_SUPPORT_MESSAGE_REQUEST = 'CREATE_SUPPORT_MESSAGE_REQUEST';
export const CREATE_SUPPORT_MESSAGE_SUCCESS = 'CREATE_SUPPORT_MESSAGE_SUCCESS'; 
export const CREATE_SUPPORT_MESSAGE_FAIL = 'CREATE_SUPPORT_MESSAGE_FAIL';

export const LIST_SUPPORT_TICKET_REQUEST = 'LIST_SUPPORT_TICKET_REQUEST';
export const LIST_SUPPORT_TICKET_SUCCESS = 'LIST_SUPPORT_TICKET_SUCCESS'; 
export const LIST_SUPPORT_TICKET_FAIL = 'LIST_SUPPORT_TICKET_FAIL';

export const LIST_SUPPORT_MESSAGE_REQUEST = 'LIST_SUPPORT_MESSAGE_REQUEST';
export const LIST_SUPPORT_MESSAGE_SUCCESS = 'LIST_SUPPORT_MESSAGE_SUCCESS';
export const LIST_SUPPORT_MESSAGE_FAIL = 'LIST_SUPPORT_MESSAGE_FAIL';

export const REPLY_SUPPORT_TICKET_REQUEST = 'REPLY_SUPPORT_TICKET_REQUEST';
export const REPLY_SUPPORT_TICKET_SUCCESS = 'REPLY_SUPPORT_TICKET_SUCCESS';
export const REPLY_SUPPORT_TICKET_FAIL = 'REPLY_SUPPORT_TICKET_FAIL'; 

export const ADMIN_REPLY_SUPPORT_TICKET_REQUEST = 'ADMIN_REPLY_SUPPORT_TICKET_REQUEST';
export const ADMIN_REPLY_SUPPORT_TICKET_SUCCESS = 'ADMIN_REPLY_SUPPORT_TICKET_SUCCESS';
export const ADMIN_REPLY_SUPPORT_TICKET_FAIL = 'ADMIN_REPLY_SUPPORT_TICKET_FAIL'; 

export const LIST_SUPPORT_TICKET_REPLY_REQUEST = 'LIST_SUPPORT_TICKET_REPLY_REQUEST';
export const LIST_SUPPORT_TICKET_REPLY_SUCCESS = 'LIST_SUPPORT_TICKET_REPLY_SUCCESS';
export const LIST_SUPPORT_TICKET_REPLY_FAIL = 'LIST_SUPPORT_TICKET_REPLY_FAIL';

export const GET_TICKET_DETAIL_REQUEST = 'GET_TICKET_DETAIL_REQUEST';
export const GET_TICKET_DETAIL_SUCCESS = 'GET_TICKET_DETAIL_SUCCESS';
export const GET_TICKET_DETAIL_FAIL = 'GET_TICKET_DETAIL_FAIL';

export const LIST_ALL_SUPPORT_TICKET_REQUEST = 'LIST_ALL_SUPPORT_TICKET_REQUEST';
export const LIST_ALL_SUPPORT_TICKET_SUCCESS = 'LIST_ALL_SUPPORT_TICKET_SUCCESS';
export const LIST_ALL_SUPPORT_TICKET_FAIL = 'LIST_ALL_SUPPORT_TICKET_FAIL'; 

export const LIST_ALL_TICKET_RESPONSE_REQUEST = 'LIST_ALL_TICKET_RESPONSE_REQUEST';
export const LIST_ALL_TICKET_RESPONSE_SUCCESS = 'LIST_ALL_TICKET_RESPONSE_SUCCESS';
export const LIST_ALL_TICKET_RESPONSE_FAIL = 'LIST_ALL_TICKET_RESPONSE_FAIL'; 

export const CLEAR_USER_SUPPORT_MESSAGE_COUNTER_REQUEST = 'CLEAR_USER_SUPPORT_MESSAGE_COUNTER_REQUEST';
export const CLEAR_USER_SUPPORT_MESSAGE_COUNTER_SUCCESS = 'CLEAR_USER_SUPPORT_MESSAGE_COUNTER_SUCCESS'; 
export const CLEAR_USER_SUPPORT_MESSAGE_COUNTER_FAIL = 'CLEAR_USER_SUPPORT_MESSAGE_COUNTER_FAIL';

export const CLEAR_ADMIN_SUPPORT_MESSAGE_COUNTER_REQUEST = 'CLEAR_ADMIN_SUPPORT_MESSAGE_COUNTER_REQUEST';
export const CLEAR_ADMIN_SUPPORT_MESSAGE_COUNTER_SUCCESS = 'CLEAR_ADMIN_SUPPORT_MESSAGE_COUNTER_SUCCESS'; 
export const CLEAR_ADMIN_SUPPORT_MESSAGE_COUNTER_FAIL = 'CLEAR_ADMIN_SUPPORT_MESSAGE_COUNTER_FAIL';
